DISTPG-318-PG14-Include dependencies for raft DCS in the Patroni package
percona/postgres-packaging pull request #123
Opened 2022-05-16 13:14 UTC by adivinho

2022-05-17 10:29 UTC, EvgeniyPatlan requested changes

2022-05-17 10:29 UTC, EvgeniyPatlan commented on patroni/patroni.spec
> +Version:        2.1.3
no. you should change Release number

2022-05-18 11:05 UTC, adivinho commented on patroni/patroni.spec
> +Version:        2.1.3
I have reverted the change.

2022-05-19 12:34 UTC, EvgeniyPatlan approved these changes

2022-05-19 12:34 UTC, merged