DISTPG-465 Add ppg-server_builder.sh, rules file for debian builds an…
percona/postgres-packaging pull request #142
Opened 2022-09-23 14:18 UTC by surbhat1595

…d update ppg-server.spec file for ppg-server meta-package builds

2022-09-23 14:23 UTC, EvgeniyPatlan approved these changes

2022-09-23 14:23 UTC, EvgeniyPatlan commented on ppg-server/ppg-server_builder.sh
> +    fi
this repo is outdated and could be removed

2022-09-23 14:23 UTC, EvgeniyPatlan commented on ppg-server/ppg-server_builder.sh
> +    fi
toolset is not needed as we don't compile anything

2022-09-23 14:23 UTC, EvgeniyPatlan commented on ppg-server/ppg-server_builder.sh
> +    rpmbuild --define "_topdir ${WORKDIR}/rpmbuild" --define "pginstdir /usr/pgsql-14" --define "dist .$OS_NAME" --define "version ${VERSION}" --rebuild rpmbuild/SRPMS/$SRC_RPM
do we need `pginstdir`?

2022-09-23 14:23 UTC, EvgeniyPatlan commented on ppg-server/ppg-server_builder.sh
> +        yum -y install llvm-toolset-7-clang llvm5.0-devtoolset
do we need llvm for metapackage build?

2022-09-23 14:23 UTC, EvgeniyPatlan commented on ppg-server/ppg-server_builder.sh
> +      DEBIAN_FRONTEND=noninteractive apt-get -y --allow-unauthenticated install libpam0g-dev || DEBIAN_FRONTEND=noninteractive apt-get -y --allow-unauthenticated install libpam-dev
go we need libpam0g-dev ?

2022-09-23 14:24 UTC, EvgeniyPatlan requested changes
please address comments

2022-09-23 15:08 UTC, surbhat1595 commented
Hi Evgeniy,

Thanks for the review comments. I have updated the requested changes now.

2022-09-23 15:10 UTC, EvgeniyPatlan approved these changes

2022-09-27 12:39 UTC, vorsel commented on ppg-server/ppg-server.spec
> +Version:        %{pgmajorversion}.%{version}
Please remove extra two spaces at the end of the line.

2022-09-29 15:13 UTC, vorsel approved these changes

2022-10-25 13:27 UTC, merged